//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by deepcopy-gen. DO NOT EDIT.

package structs

import (
	api "github.com/cilium/cilium/pkg/policy/api"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatapathEndpoint) DeepCopyInto(out *DatapathEndpoint) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatapathEndpoint.
func (in *DatapathEndpoint) DeepCopy() *DatapathEndpoint {
	if in == nil {
		return nil
	}
	out := new(DatapathEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtMeta) DeepCopyInto(out *ExtMeta) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtMeta.
func (in *ExtMeta) DeepCopy() *ExtMeta {
	if in == nil {
		return nil
	}
	out := new(ExtMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtNetworkPolicy) DeepCopyInto(out *ExtNetworkPolicy) {
	*out = *in
	in.ExtMeta.DeepCopyInto(&out.ExtMeta)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtNetworkPolicy.
func (in *ExtNetworkPolicy) DeepCopy() *ExtNetworkPolicy {
	if in == nil {
		return nil
	}
	out := new(ExtNetworkPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtNetworkPolicyNodeStatus) DeepCopyInto(out *ExtNetworkPolicyNodeStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtNetworkPolicyNodeStatus.
func (in *ExtNetworkPolicyNodeStatus) DeepCopy() *ExtNetworkPolicyNodeStatus {
	if in == nil {
		return nil
	}
	out := new(ExtNetworkPolicyNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtNetworkPolicyStatus) DeepCopyInto(out *ExtNetworkPolicyStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make(map[string]ExtNetworkPolicyNodeStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtNetworkPolicyStatus.
func (in *ExtNetworkPolicyStatus) DeepCopy() *ExtNetworkPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ExtNetworkPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtPolicyRule) DeepCopyInto(out *ExtPolicyRule) {
	*out = *in
	in.ExtMeta.DeepCopyInto(&out.ExtMeta)
	if in.Rule != nil {
		in, out := &in.Rule, &out.Rule
		*out = new(api.Rule)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtPolicyRule.
func (in *ExtPolicyRule) DeepCopy() *ExtPolicyRule {
	if in == nil {
		return nil
	}
	out := new(ExtPolicyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPToIdentity) DeepCopyInto(out *IPToIdentity) {
	*out = *in
	in.IP.DeepCopyInto(&out.IP)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPToIdentity.
func (in *IPToIdentity) DeepCopy() *IPToIdentity {
	if in == nil {
		return nil
	}
	out := new(IPToIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L4Policy) DeepCopyInto(out *L4Policy) {
	*out = *in
	if in.SourceRules != nil {
		in, out := &in.SourceRules, &out.SourceRules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L4Policy.
func (in *L4Policy) DeepCopy() *L4Policy {
	if in == nil {
		return nil
	}
	out := new(L4Policy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Node) DeepCopyInto(out *Node) {
	*out = *in
	in.ExtMeta.DeepCopyInto(&out.ExtMeta)
	in.Address.DeepCopyInto(&out.Address)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Node.
func (in *Node) DeepCopy() *Node {
	if in == nil {
		return nil
	}
	out := new(Node)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelectorPolicy) DeepCopyInto(out *SelectorPolicy) {
	*out = *in
	in.L4Policy.DeepCopyInto(&out.L4Policy)
	out.Labels = in.Labels.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelectorPolicy.
func (in *SelectorPolicy) DeepCopy() *SelectorPolicy {
	if in == nil {
		return nil
	}
	out := new(SelectorPolicy)
	in.DeepCopyInto(out)
	return out
}
